export const Emojis = {
  "Music Note": "🎵" as const,
  "Musical Notes": "🎶" as const,
  "Musical Score": "🎼" as const,
  Microphone: "🎤" as const,
  Headphone: "🎧" as const,
  "Musical Keyboard": "🎹" as const,
  Drum: "🥁" as const,
  Guitar: "🎸" as const,
  Violin: "🎻" as const,
  Trumpet: "🎺" as const,
  "Studio Microphone": "🎙️" as const,
  "Level Slider": "🎚️" as const,
  "Control Knobs": "🎛️" as const,
}
